### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by codepotato** [Freegle/iznik-nuxt#1]
Just getting my version up to date and I get the above error. Did you kill something @edwh

**Comment by edwh** [comment]
PRobably.  Need a bit more info - what page you're at, call-stack...

------ Original Message ------

**Comment by codepotato** [comment]
Literally the homepage, just tried to view it in a browser and bam big error

**Comment by edwh** [comment]
Ah, logged out bug I introduced.  Fixed.

**Comment by codepotato** [comment]
Working. Ta

**Comment by edwh** [comment]
There was another logged out problem when moving pages - just pushed that fixed.
