### ISSUE TITLE
Help page uses hard links

### ISSUE THREAD

**Issue by chriscant** [Freegle/iznik-nuxt#118]
help.vue contains hard links (not nuxt-link) which don't work in mobile app and cause a page load on the web

**Comment by edwh** [comment]
This is a consequence of the plugin that is used to generate the accordion - it operates at run time and can therefore only insert something which will work at that point.  So nuxt-link wouldn't work (I tried that first).

I'm not bothered about the page load in this case, but obviously we need to find a way for it to work on the mobile app.  <nuxt-link> ends up being a relative <a> link on the web - what is it that makes <nuxt-link> work for you when <a> doesn't? ?

**Comment by edwh** [comment]
Fixing in #140 .
