### ISSUE TITLE
Use bootstrap mixin breakpoints

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt#122]
This is neater than redefining them.  It applies in quite a few places.

- [ ] global.scss where we define our own duplicates, and then when we use those definitions later in the file.
- [ ] pages/stats/_groupname where we redefine $bootstrap-sm and use it
- [ ] default.vue ditto
- [ ]

**Comment by JayyajGH** [comment]
@edwh - I believe these have now been replaced everywhere.  Can we now close this issue?

**Comment by edwh** [comment]
We can indeed.  Thanks.
