### ISSUE TITLE
Add better page not found page

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt#163]
It looks like this:

![image](https://user-images.githubusercontent.com/56696/72080198-43418d80-32f4-11ea-8440-b2628707c965.png)

Could be prettier.

Also log sentry exception.

**Comment by JayyajGH** [comment]
@edwh 

Do you have an idea of what you want this to look like?  Do you have any Freegle imagery that could be used? The only things I can find are the Freegle A4 poster.

I was thinking of a slightly fun 404 page.  Something like "That page doesn't seem to exist.  Maybe it's been Freegled.  Click here to go back to the home page".

**Comment by edwh** [comment]
I have no idea, but yes, definitely something fun.  Perhaps a cartoon of 
someone looking comically horrified?

Also add a link to support@ilovefreegle.org for people to report 
problems.

------ Original Message ------
