### ISSUE TITLE
Availability checkmarks don't change state on click if schedule never edited before

### ISSUE THREAD

**Issue by prcmt** [Freegle/iznik-nuxt#184]
I don't seem to be able to edit my availability on Freegle. Clicking the checkmarks doesn't seem to do anything (see below).

![output](https://user-images.githubusercontent.com/59378788/73197026-8be8ab80-4128-11ea-8efd-135808c8b3bf.gif)

* I get the same behavour on Safari, the latest Firefox, and Firefox ESR, across macOS and Linux.
* I do not get any javascript console errors.
* Same behaviour on a fresh checkout of master.

**Comment by edwh** [comment]
Thanks for the very clear report.  

I can't repro that.  Can you narrow it down by adding console logs into toggle() in AvailabilityModal?

**Comment by prcmt** [comment]
I did a little digging I think that this is a more accurate description of the problem:

If the user has never set a schedule before (`this.schedule.schedule == []`), the checkmarks do not change colour when clicked - so it appears as if nothing is happening. This is what confused me. In actual fact, if you save your changes then they made and from then on the checkmarks do change colour when clicked.

![output](https://user-images.githubusercontent.com/59378788/73200237-4af39580-412e-11ea-9b21-decdab700cb1.gif)

**Comment by edwh** [comment]
Ah, excellent.  I'll look at that.

------ Original Message ------

**Comment by edwh** [comment]
I've fixed this, although not in a way that I'm especially proud of.  Thanks very much for reporting this so clearly and helping track it down.

**Comment by prcmt** [comment]
Thank you for the very quick fix. 😄
