### ISSUE TITLE
Explore improvements

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt#194]
- [x] The region buttons should cause us to zoom the map to the appropriate place.

**Comment by JayyajGH** [comment]
@edwh - Just taking a quick look at this one.  It looks like the list of regions comes from an API.  Can we get that API to also return the coordinates for the centre of the region?  I can't see that data anywhere at the moment.

**Comment by edwh** [comment]
We don't have them.  Each group is just manually flagged as being in a 
region.  I guess we could reverse engineer the centre from the current 
list of groups which are inside the area...

...but I don't think it's the way to go.  In the old code we tended to 
find a bounding box from a set of objects:

var swlat = 0, swlng = 0, nelat = 0, nelng = 0, clat = 0, clng = 0
var bounds = new google.maps.LatLngBounds()
self.collection.each(function (group) {
var lat = group.get('lat')
var lng = group.get('lng')
swlat = lat < swlat ? lat : swlat
   swlng = lng < swlng ? lng : swlng
   nelat = lat > nelat ? lat : nelat
   nelng = lng > nelng ? lng : nelng
   bounds = bounds.extend(new google.maps.LatLng(lat, lng))
})

...and then we had a function I must have got from somewhere to work out 
the zoom level from bounds + size of map:

var mapDim = {
height: self.$('.js-map').height(),
width: self.$('.js-map').width()
}

var zoom = Iznik.getBoundsZoomLevel(bounds, mapDim)

Iznik.getBoundsZoomLevel = function (bounds, mapDim) {
var WORLD_DIM = {height: 256, width: 256}
var ZOOM_MAX = 21

function latRad (lat) {
var sin = Math.sin(lat * Math.PI / 180)
var radX2 = Math.log((1 + sin) / (1 - sin)) / 2
return Math.max(Math.min(radX2, Math.PI), -Math.PI) / 2
}

function zoom (mapPx, worldPx, fraction) {
return Math.floor(Math.log(mapPx / worldPx / fraction) / Math.LN2)
   }

var ne = bounds.getNorthEast()
var sw = bounds.getSouthWest()

var latFraction = (latRad(ne.lat()) - latRad(sw.lat())) / Math.PI

var lngDiff = ne.lng() - sw.lng()
var lngFraction = ((lngDiff < 0) ? (lngDiff + 360) : lngDiff) / 360

var latZoom = zoom(mapDim.height, WORLD_DIM.height, latFraction)
var lngZoom = zoom(mapDim.width, WORLD_DIM.width, lngFraction)

return Math.min(latZoom, lngZoom, ZOOM_MAX)
}

So that way the map zooms out far enough to hold the things you're 
trying to show for all screens.  I think what I had in mind here was to 
reimplement code similar to this.

------ Original Message ------

**Comment by JayyajGH** [comment]
I meant the list of regions at the top of the explore page e.g. East, Scotland, South West etc.  Are they not brought back from an API?  Or are you saying that a moderator could create a group in Cornwall and tag it with a region of "Really really South West" and then that would appear in the list.

**Comment by edwh** [comment]
Yes, those regions.  There is a set list of them, but it's just an 
enumeration and each group has one of the values.

That issue is saying that when you click on North East, instead of 
seeing:


...you should see:


So in order to decide which area of map to show, you need to find a 
bounding box, then find a zoom level which will show all of that 
bounding box.    Having the centre of the region wouldn't really help 
with that - it would allow you to centre the map at the right place, but 
it wouldn't tell you how far to zoom in.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah that makes sense.  But you could store the centre coordinates and the zoom level for each region and return a more detailed object instead.  For each of those regions I can find a sweet spot of centre and zoom level fairly easily.

Anyway, if that's not your preference then can this data be returned from the server?  i.e. put the logic you mentioned in the backend API rather than calculating this on the front-end? 

Rather than the API returning:

regions: {
 1: South West
 2: North
}

regions: {
 1: {
    name: 'South West",
    centre: lat/long coordinates,
    zoom: 6
  },
2: {
    name: 'North",
    centre: lat/long coordinates,
    zoom: 3
  }
}

**Comment by edwh** [comment]
Think of it by width with all groups running east to west.

If you're on a desktop, then zoom 10 might show everything you need.  If 
you have a narrower screen, you need to zoom out so that everything fits 
on that screen.

So the server can't determine the zoom level required to show everything 
on the size of the screen that the client has.

------ Original Message ------

**Comment by JayyajGH** [comment]
Ah yes screen size.  Doh!

**Comment by edwh** [comment]
:-)

**Comment by JayyajGH** [comment]
I've just been taking a look at this and it might end up being quite simple.  I've never used the map API before and it's not the easiest thing to get to grips with!  Unless I'm just having a tough Friday!

So I just called fitBounds passing in the groupsInBounds lat/lng coordinates after using extend and it all just seems to work out of the box.  The map is zoomed in as required.  The code running in "Idle" messes it up though as that is zooming it back out again so I need to look deeper.  e.g. if I switch out the "idle" code for the code below then it works..  I'll investigate further on Monday.

`  const google = gmapApi()

      const latlngbounds = new google.maps.LatLngBounds()

      this.groupsInBounds.forEach(group => {
        latlngbounds.extend(new google.maps.LatLng(group.lat, group.lng))
      })

      this.$refs.gmap.$mapObject.fitBounds(latlngbounds)
      return latlngbounds`

**Comment by edwh** [comment]
fitBounds might indeed do it.  I guess try on different screen sizes...

------ Original Message ------

**Comment by edwh** [comment]
@JayyajGH has done this now.
