### ISSUE TITLE
Cookie samesite policy is incorrect

### ISSUE THREAD

**Issue by JayyajGH** [Freegle/iznik-nuxt#272]
![image](https://user-images.githubusercontent.com/17859423/83609628-74a64880-a576-11ea-8922-40204ed174a7.png)

**Comment by JayyajGH** [comment]
The console mentioned errors with google.com and facebook.com

**Comment by edwh** [comment]
Erm, ok.  But do you know what we need to do?

------ Original Message ------

**Comment by JayyajGH** [comment]
I've fixed it on our work site by some settings in the web.config file but that was an ASP.NET MVC site so it is likely to be different here.  This was all caused by the Chrome 80 release.

https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html

Basically if you don't specify the samesite policy then it defaults to "lax" so won't be available in a third party context.  You can fix it by setting samesite to be "none" but that all depends on how the cookies are created.

I think the first step is finding the cookies in question.  On the "My Posts" pages the cookies causing warnings are two from google, one from facebook and one from inspectlet.  It could be all wrapped up in various NPM packages that need updating.

**Comment by edwh** [comment]
I'm a bit unclear whether we need to do anything.

We pull in some libraries from Facebook (e.g. their SDK) and google 
(e.g. analytics) and inspectlet (for session reply sampling).  Those get 
pulled in as scripts - I've checked the code, but also if they were npm 
packages then they would be on our domain and therefore (I think) not 
able to set those cookies anyway.

So:
They will continue to work, in which case we don't care.They will get 
fixed soon, in which case we don't care.They will break horribly, in 
which case lots of people will be affected, not just us, and then either 
they'll get fixed, or the web will be full of the solution.
Make me care :-).

------ Original Message ------

**Comment by JayyajGH** [comment]
I'm unclear too.  I just saw the warning in the console and know that at some point chrome is going to block reading cookies that don't follow the rules.  Google have been warning everyone for the last year saying that it might break websites.

Basically cookies are becoming secure by default rather than unsecure by default.  What the warning is telling us is that we are using cross site cookies but not specifically that we want them so in the future they will be blocked.

The thing I don't know is where these cookies come from and who sets them.  Is it those three companies that are creating them in their libraries and the libraries need updating?  Or do we need to do something on this site?

**Comment by edwh** [comment]
It's their problem.

https://stackoverflow.com/questions/60337016/samesite-attribute-and-facebook-sdk

It would be our problem if we set the cookie, but I don't think we could 
set a cookie for another domain anyway.

It's worth Chrome telling us about because if we relied on something 
from (say) another domain that we owned, then it would be within our 
power to fix.  Or if it was something we could contact our supplier 
about.

But for these cases, I don't think we do anything.  They will either be 
on the case or it's not an issue for some reason.

------ Original Message ------

**Comment by JayyajGH** [comment]
That makes sense. I know that one was for Facebook but it seems odd that Google haven't updated their login process as they are the ones pushing it. Is it just that we need to update our libraries though? I can look into that tomorrow if you don't know.

**Comment by edwh** [comment]
No, I don't think we do.  Inspectlet isn't versioned, for example.  
Facebook's SDK is, but they force you up versions over time, and I tried 
setting the version to the latest one and still got the warning.

------ Original Message ------

**Comment by JayyajGH** [comment]
Ok so I guess we just add a javascript loader which then loads the actual code so they control it.

Just been googling about the Google signin and people seem very confused.  How can google be pushing this but not updating their own code?

Do you want to leave this issue around or to close it?

**Comment by edwh** [comment]
Exactly.

I'll close it, as I'm not going to do anything unless/until it breaks horribly.  When it does, you can distract me from fixing it by jumping up and down and saying "Told you so!".
