### ISSUE TITLE
"null" displayed on Job Search titlebar

### ISSUE THREAD

**Issue by emacstheviking** [Freegle/iznik-nuxt#289]
On initial page load the value for the location is obviously not set so the template needs to not display anything until a value exists, otherwise it says "null" as the screenshot shows. Once you enter a location everything is fine again.

https://snipboard.io/HbBmEi.jpg

**Comment by edwh** [comment]
Thanks.  It's valid to go to that page without a location specified - if logged in it will use your own if it has one, or none.  But the title is wrong, as you've spotted.  Thanks.
