### ISSUE TITLE
Improve use of H1 etc for accessibility

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt#291]
H1, H2 etc are heavily used by screenreaders for navigation, and so are important for accessibility.  They also control the prominence of headings on the screen.

There are places on the site where we skip headings, e.g. drop immediately to H3.  This is because H1 or H2 would look too shouty for the layout.  But it is not good for accessibility.

We should introduce global classes to control the visual appearance and then use H1 etc for semantics.  This would improve accessibility.

**Comment by edwh** [comment]
@JayyajGH , you should maybe ref this in checkins.

**Comment by JayyajGH** [comment]
Actually I think the majority of these are now fixed. Certainly on the main pages.

**Comment by edwh** [comment]
Shall we close this, then?

**Comment by JayyajGH** [comment]
Yeah I think we probably should.  The main pages are all good.
