### ISSUE TITLE
Availability picker does not work

### ISSUE THREAD

**Issue by plinkpaste** [Freegle/iznik-nuxt#309]
![image](https://user-images.githubusercontent.com/7480500/91973790-bb8e1080-ed14-11ea-9942-2da3582a8c70.png)

4 errors are present in the console, if they are relevant:

![image](https://user-images.githubusercontent.com/7480500/91973856-d52f5800-ed14-11ea-9b03-7fd3f00af712.png)

**Comment by edwh** [comment]
Thanks for the report.  Where are you opening this from - is it 
Settings, or from Chat?

------ Original Message ------

**Comment by plinkpaste** [comment]
Hi, I've tried both and get the same result.

-------- Original Message --------

**Comment by edwh** [comment]
Thanks.  It may be specific to the existing data for your user.  If you 
can let me know what your Freegle email is (mail to to 
geeks@ilovefreegle.org) then I'll check that out.

If you fancy upgrading from Angular to Vue (ducks and runs) you might 
like to try getting a dev env up and running.

------ Original Message ------

**Comment by edwh** [comment]
Hi there - can you let us know which user you are?

Also which browser you're using, please.

**Comment by plinkpaste** [comment]
Username is Osarius.
I use Chrome, specifically at the moment v 85.0.4183.102.

It also doesn't work in the Freegle Android app, presumably because it's just a webview container loading the website.

**Comment by edwh** [comment]
Thank you.  I can see the problem, so I've fixed that, and tested it on your account to make sure it opens ok.

I've also fixed the data in your specific account, so you should be able to use that feature now.

**Comment by plinkpaste** [comment]
Perfect, thank you!

**Comment by edwh** [comment]
You're welcome - thanks for reporting the problem.

------ Original Message ------
