### ISSUE TITLE
Editing issue - postcode is always replaced with the poster's own regardless of what was in the post

### ISSUE THREAD

**Issue by camopants** [Freegle/iznik-nuxt#365]
Possibly something of an edge case, but I have for several months been giving away stuff from a location not my own, and every time I edit I have to manually over-ride my default home postcode, which I often forget to meaning the post changes to the wrong location.  I could change my home location, but ideally once the form is populated for an existing offer it should retrieve the previously recorded location, not assume the poster's.

**Comment by edwh** [comment]
Hi there, and thanks for the report.

Are you talking specifically about editing, or about reposting?

There are restrictions on which communities people can use at the moment, during COVID, so it's possible they may be having that effect, though I'll need to check that.

**Comment by camopants** [comment]
Specifically, going into an existing posting to change the substance, and finding that the postcode has reverted by itself.  The item post code and my own are within the same group/boundary, so that is not the problem.

(As an aside, not related to this issue, I can tell you people are completely ignoring group boundaries. I have had enquiries from 50 miles away, so the distance restrictions are evidently not working.)

**Comment by edwh** [comment]
Ok, I'll have a look at the edit case.  Thanks.

The distance restrictions can only be applied when we know the locations 
of both parties, and for replies on the web on our own website rather 
than for TrashNothing users.  So you're right, there will be some that 
will get through, but it's stopped a bunch too.

------ Original Message ------
From: "camopants" ***@***.***>
To: "Freegle/iznik-nuxt" ***@***.***>
Cc: "Edward Hibbert" ***@***.***>; "Comment" 
***@***.***>
Sent: 17/03/2021 13:47:26
Subject: Re: [Freegle/iznik-nuxt] Editing issue - postcode is always 
replaced with the poster's own regardless of what was in the post (#365)

**Comment by edwh** [comment]
Straightforward fix, should go live in a day or two.  Thanks.
