### ISSUE TITLE
Need to be able to promise items to correspondents possibly not linked to item

### ISSUE THREAD

**Issue by camopants** [Freegle/iznik-nuxt#366]
People often ask "can I have this, but can I also have...".

When marking items promised, if they don't then retrospectively mark their interest in the other items, it is currently impossible to mark the item as promised, leading other people to continue to ask.  For popular items this means either being rude and ignoring following enquiries, or having to field repetetive apologetic answers.

**Comment by edwh** [comment]
I think you should be able to do that.  If you click the Promise button in the Chat window there's a drop-down you can use to select an item to promise.

**Comment by edwh** [comment]
![image](https://user-images.githubusercontent.com/56696/111514564-c442b300-8749-11eb-89fe-6d631cdb3834.png)

**Comment by camopants** [comment]
But unless I'm missing something you can't access that without first unpromising the current item, and if you try it on any other item it only allows you to promise to the people involved in chats on that item.

**Comment by camopants** [comment]
Ah, OK, it depends on HOW you access the change. You can't do it from the chat with a person on an item, but if you access the global chat you can.

OK.  So, a UI consistency thing rather than a technical fault.
