### ISSUE TITLE
Displays wrong photo

### ISSUE THREAD

**Issue by ChrisOfBristol** [Freegle/iznik-nuxt#375]
I posted an offer with a photo a while ago, then withdrew it.
I have now posted a new and completely different offer and included an image. The image that showed was from the earlier post, after clicking "See Details" the correct one showed as the second phtotgraph. Deleting the incorrect one results in no image showing until I click "See Details" when the correct one shows.

https://www.ilovefreegle.org/message/80990129

**Comment by edwh** [comment]
Thanks. Do you remember which the earlier post was?

Draft unsubmitted posts are saved. So if you went to the post page a bit later, and edited a draft post but didn't notice the existing photo, that could happen. We've had some examples of that. Might that have happened for you? 

The details shown on the summary have a slight lag. Is the photo showing for you now?

**Comment by ChrisOfBristol** [comment]
The previous post was #79418930. There were no draft posts. 
The correct image eventually showed on the front page, but the lag is very confusing for the user.
What's worse is that initially an image was shown from another of my posts which was for something completely different.

**Comment by edwh** [comment]
Thanks. I'll dig back in the logs and see what I can find.

**Comment by edwh** [comment]
@ChrisOfBristol when you say "on the front page", which specific URL do you mean?

**Comment by edwh** [comment]
Notes to self.

API logs show that the second message was created with two photos:

`{"call":"message","collection":"Draft","locationid":8031243,"messagetype":"Offer","item":"Samsung Colour Laser Printer","textbody":"Samsung CLP-315 colour laser printer\n\nPrints are very blurry at the moment as it has been sitting around getting dusty, hopefully it will clear if you run through several black and white pages. \n\nNo wireless. Includes mains and USB leads. Width 385mm, height 245mm, depth 310mm and tray sticks out the front a further 55mm. I will email the manual and the drivers are available online. \n\nPrompt collectors will be preferred.","availablenow":1,"attachments":[19788755,20383322],"groupid":253538,"email":"XXX","modtools":false,"type":"PUT"}`

19788755 no longer exists but probably dates from around the start of May, so it's definitely an old photo.  Images are cached in local storage indexed by message id; for unsubmitted messages these are -1, -2 etc.  to avoid linking images to the wrong message.

Web server logs show a fetch of that old photo from the /give page at 08/Jun/2021:15:06:28 UTC, shortly before the post of the next photo at 2021-06-08 15:10:47, and submission of the second message at 2021-06-08 15:10:47.  

That's what I'd expect if it was loading an old draft post in, and then Chris went on two add a second photo and complete the submission.  That's not what Chris recalls, obviously.

We don't have backups or web logs from the time the original photo was created; the oldest is 12th May.  I've restored that, and it doesn't shed any light on the older post.

**Comment by edwh** [comment]
@ChrisOfBristol I've investigated this as much I as I can.  It's consistent with an old draft stored on the client side with a photo in it, and then you not noticing that and going on to add another photo and post it.  I'm aware that wasn't what you remember, so apologies if it's annoying to suggest that.  There isn't much more debugging I can do on this one, I'm afraid.
