### ISSUE TITLE
Encoding error with adverts

### ISSUE THREAD

**Issue by edent** [Freegle/iznik-nuxt#380]
Saw this advert on the Freegle site. There's a bit of mojibake in the middel.
![Screenshot 2021-09-04 at 15-17-26 Chats](https://user-images.githubusercontent.com/837136/132097667-8efec9df-041f-4b4b-8d11-0f959bb8c18b.png)

For some reason, the en-dash `–`  U+2013  has been misencoded.

Original advert at https://www.totaljobs.com/job/php-developer/rbw-consulting-limited-job93874864?WT.mc_id=A_RE_C4JPPC_MP1_C11_18_TJ

Also means the £ sign is broken as well.
![Screenshot from 2021-09-04 15-25-02](https://user-images.githubusercontent.com/837136/132097800-1cd96ee2-e51d-4e8d-bac0-36692cc46b85.png)

**Comment by edwh** [comment]
Thanks. These come from a partner which aggregates them, so some do get a
bit mangled along the way. I'll have a look and see if we can improve this.
