### ISSUE TITLE
Inform user if they have contacted another user previously

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#382]
Sometimes I reply to a WANTED or OFFER post without realising or remembering that I have dealt with that person before, maybe a year or more ago. *After* I send the reply, the chat shows the previous conversation, and I have an "aha" moment.

It would be nice if we could somehow be informed *before* we send a reply, also giving us the ability to view the previous chat, a bit like how eBay has a thing where it says "Seller you have bought from before" when viewing an item.

Thanks!

**Comment by edwh** [comment]
Thanks, that's a useful suggestion that I hadn't thought of.  It should be possible; I'll put it on my TODO list...unless you fancy coding it :-).

**Comment by JohnVeness** [comment]
I'm not a developer, sorry!

I have thought of a potential downside, though. If the user clicks to view the previous chat, they might be tempted to reply about the new item there, rather than replying in the item listing. This will mean there will be no link in the chat to the new item, so it cannot be "Promised" etc.

In fact, that raises another thought, which I have just mentioned in issue #384.

**Comment by edwh** [comment]
You can promise any item using the button in Chat - there's an item dropdown.  It doesn't need to have had a reply to the original listing for you to do that.

**Comment by edwh** [comment]
This will appear soon:

![image](https://user-images.githubusercontent.com/56696/149746757-4c6763da-0348-420d-b947-6d462ab9895e.png)
