### ISSUE TITLE
"Connected before" shows even if you've only opened (but never sent or received) a chat with someone

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#389]
Hi, many thanks for implementing the "Connected before" feature, as discussed in #382. However, I wonder if it's currently too "sensitive"!

Before the "Connected before" banner, what I used to do before replying to a post was to click on the member's profile, then the Message button in top-right, which would show me any previous chat with the member. However, I notice that if I do that now (and I still do it out of habit), and the chat is empty (meaning I never connected to the member previously) the post now says "Connected before", even if I never actually typed any message!

Are you able to change it so that it only says "Connected before" if you've actually sent or received a message to/from the member? Thanks!

**Comment by edwh** [comment]
That's a good suggestion.

Fixed in the server in https://github.com/Freegle/iznik-server/commit/209c0030efc11079faef2403847f342973cfb343.
