### ISSUE TITLE
Show text of an item when viewing a chat

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#390]
At the moment, if you reply to someone's item post, the chat will show a small view of the item - a thumbnail pic, the title, location, the time and which Freegle community. I realise that you can click on the item and see the full post details, but it would be very helpful if the full text of the post could be included in the chat, without having to click through. No need to have all the photos and the map in the chat, but the full post text would often be very helpful, and would fit in well (i.e. not seem out of place) with the rest of the chat, I think.

**Comment by edwh** [comment]
Thanks for the suggestion.  I'm not quite sure how this would work.  Sometimes the text is extremely long, and showing it all would be excessive, especially on mobile.  So we'd have to truncate it, which means that you'd often have to do a click anyway.

**Comment by JohnVeness** [comment]
Obviously you could access the database to analyse the full stats, but in my experience, most descriptions aren't "too long" (by some subjective definition of that!)

**Comment by edwh** [comment]
It's not unreasonable to assume that you broadly remember what it is you've expressed interest in.  If there is some other detail, then you can click through.  If there is so little info that you can fit it all in the chat without truncation, then it's hard to see that there is any meaningful info that you're adding.

I don't think I'm going to do this one, I'm afraid.
