### ISSUE TITLE
Email copies of chat messages remove exclamation marks

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#391]
I've noticed that email copies of chat messages replace exclamation marks with full stops. This can sometimes make the email copy of the chat message seem drier than it was intended! Presumably this wasn't accidental, but I wonder if this can be reviewed and hopefully changed?

**Comment by edwh** [comment]
This is intentional, because exclamation marks increase the chance of messages being considered spam.  That means the mail is more likely to be missed, and also damages our overall email reputation.
