### ISSUE TITLE
Portrait photos are cropped on landscape screens

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#397]
When viewing an item such as https://www.ilovefreegle.org/message/88557903 on a typical landscape desktop monitor, it is not obvious that the photo has been cropped. This is the case even when clicking "View larger image". The only way to see the full image is to right-click on it and view it in a new tab (in Firefox for example).

In this particular case there is nothing significant cut off, but sometimes there will be important parts of the image chopped off the top and bottom that the viewer will not even be aware of.

**Comment by edwh** [comment]
Thanks.  There's supposed to be a photo zoomer, but it was wrongly not showing when there was just one image.

**Comment by JohnVeness** [comment]
Thanks, the full image is showing when clicking "View larger image" now. I now notice a problem with the zoomer, which I'm not sure if new or not, but I'll add that as a new issue.
