### ISSUE TITLE
Email copies of chat messages don't get sent sometimes

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#406]
Hello again. I have noticed a few occasions when I don't receive an email copy of a chat message, or an "Item promised" message. I *think* this happens if I'm actively looking at the chat on the website when the message appears.

I'm assuming the site thinks I only need to be notified about messages I haven't seen on the site, which sounds reasonable at first glance, but I like to have a full record of the conversation in my email which I can access offline - sometimes addresses or other important information doesn't get through and I have to check the site.

Thanks.

**Comment by edwh** [comment]
Yes, this is by design.  Most people don't like getting by email something they have already seen.  This isn't what you want, but you're in the minority, I'm afraid.
