### ISSUE TITLE
"What the enter key does" setting sometimes reverts

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#407]
Every now and then (after some weeks), I find that the "What the enter key does" setting changes from my preferred "Insert new line" to "Send message".

I haven't managed to spot a pattern as to when or why this happens, but it's happened several times to me over the last year, say. Using the same browser profile throughout.

I've not noticed any other settings having this problem.

**Comment by edwh** [comment]
Which browser are you using?

------ Original Message ------
From "John Veness" ***@***.***>
To "Freegle/iznik-nuxt" ***@***.***>
Cc "Subscribed" ***@***.***>
Date 26/06/2022 18:36:41
Subject [Freegle/iznik-nuxt] "What the enter key does" setting sometimes 
reverts (Issue #407)

**Comment by JohnVeness** [comment]
Firefox, currently version 101.0.1

**Comment by edwh** [comment]
Thanks. This is stored in local storage and I have quite often seen Firefox lose local storage on exit. Chrome less so. 

It's probable this will move out of local storage in the next version, along with other information.

**Comment by JohnVeness** [comment]
Thanks. Do you know exactly which bit of local storage it's stored in? I'm looking in F12 but am having trouble finding it.

**Comment by edwh** [comment]
It is probably in IndexedDB, though it might be in local storage if access to that fails.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/56696/175833377-f7b8317c-47a8-48c9-b7d2-8129c84c4e26.png">
