### ISSUE TITLE
Single page application issues

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt#416]
Hi. I'm not a web expert, but I believe this app mostly works as a "single page application". I guess this has some advantages, but I find it visually annoying with popup windows on top of other popup windows.

I would prefer to be able to open particular posts in a new tab, but can't easily do that. For example, if I'm browsing a particular Freegle group, I can click on an interesting post to view it in a popup, but the URL doesn't change in the address bar, and I can't right-click on the post to open it in a new tab, etc.

I know that individual posts *can* have individual full-page URLs, of the form https://www.ilovefreegle.org/message/xxxxxxxx, as I see them in email notifications from the site, but it doesn't seem to be easy to get to those URLs from the site itself.

Similarly, I cannot find at all how to open a particular user's profile (i.e. all their current posts) in a new tab, which is also something I'd like to be able to do from time-to-time.

Thanks for reading!

**Comment by edwh** [comment]
@JohnVeness The codebase you're using is https://github.com/freegle/iznik-nuxt3 now - this project is only used for moderator tools.  

I've made a change so that you can right-click on the item title and open in a new tab.  See how that works for you.

I've not done anything about the profile one. You could open a new issue for that in iznik-nuxt3.

**Comment by JohnVeness** [comment]
Thanks for that. Argh, sorry, I keep getting the repos mixed up. Maybe the readme of this one could be updated?

Discussion continued in https://github.com/Freegle/iznik-nuxt3/issues/81

**Comment by edwh** [comment]
Good point, I've updated the readme.
