### ISSUE TITLE
Landscape home screen boggling

### ISSUE THREAD

**Issue by chriscant** [Freegle/iznik-nuxt#89]
On an old iPad2 in Safari in landscape mode the logged in home screen is too busy: mainly the sidebars. The old site has a similar layout - and worse with the advert at the top.

![IMG_0769](https://user-images.githubusercontent.com/1153272/70992052-bde60700-20c0-11ea-8502-1f2c32c5c38b.PNG)
![IMG_0772](https://user-images.githubusercontent.com/1153272/70992054-bde60700-20c0-11ea-8805-461f575b8a32.PNG)

**Comment by edwh** [comment]
Addressed by Simple View toggle.
